name: "Build Gradle project"
on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java-version: [ 8, 11, 16 ]
                gradle-version: [ 6.0.1, 6.9, 7.0.2, 7.2 ]
        name: Test JVM/Gradle (${{ matrix.java-version }}, ${{ matrix.gradle-version }})
        steps:
            -   name: Check out project
                uses: actions/checkout@v2
            -   name: Set up JDK 11
                uses: actions/setup-java@v1
                with:
                    java-version: 11
            -   name: Build with Gradle
                uses: gradle/gradle-build-action@v1
                with:
            arguments: build -PtestJavaRuntimeVersion=${{ matrix.java-version }} -PtestGradleVersion=${{ matrix.gradle-version }} -Pgradle-build-scan-teamcity-plugin.acceptGradleTOS=true
            distributions-cache-enabled: true
            dependencies-cache-enabled: true
            configuration-cache-enabled: false
